# Generated by Django 4.1 on 2022-09-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainFunctionTable',
            fields=[
                ('function_id', models.BigIntegerField(db_column='Function_ID', primary_key=True, serialize=False)),
                ('function_name', models.CharField(db_column='Function_Name', max_length=255)),
            ],
            options={
                'db_table': 'Main_Function_Table',
            },
        ),
        migrations.CreateModel(
            name='SubFunctionTable',
            fields=[
                ('function_name', models.CharField(db_column='Function_Name', max_length=255)),
                ('sub_function_id', models.BigIntegerField(db_column='Sub_Function_ID', primary_key=True, serialize=False)),
                ('sub_function_name', models.CharField(db_column='Sub_Function_Name', max_length=255)),
                ('function', models.ForeignKey(db_column='Function_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='EMS_Database.mainfunctiontable')),
            ],
            options={
                'db_table': 'Sub_Function_Table',
            },
        ),
        migrations.CreateModel(
            name='SubFunctionSubscriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_function_name', models.CharField(db_column='Sub_Function_Name', max_length=255)),
                ('sub_type', models.CharField(db_column='Sub_Type', max_length=100)),
                ('status', models.BooleanField(db_column='Status')),
                ('sub_function', models.ForeignKey(db_column='Sub_Function_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='EMS_Database.subfunctiontable')),
            ],
            options={
                'db_table': 'Sub_Function_Subscription_Table',
            },
        ),
        migrations.CreateModel(
            name='MainFunctionSubscriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(db_column='Function_Name', max_length=255)),
                ('sub_type', models.CharField(db_column='Sub_Type', max_length=100)),
                ('status', models.BooleanField(db_column='Status')),
                ('function', models.ForeignKey(db_column='Function_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='EMS_Database.mainfunctiontable')),
            ],
            options={
                'db_table': 'Main_Function_Subscription_Table',
            },
        ),
    ]
