# Generated by Django 4.1 on 2022-09-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_storage_size_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='sub_type',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Guest', 'Guest')], default='Guest', max_length=100),
        ),
    ]
