# Generated by Django 4.1 on 2022-09-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_storage_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='storage_size_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
