# Generated by Django 4.1 on 2022-09-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_storage_size_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='storage_size_id',
            new_name='storage_size',
        ),
    ]
