# Generated by Django 4.1 on 2022-09-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_storage_size_id_user_storage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_limit',
            field=models.BigIntegerField(),
        ),
    ]
