# Generated by Django 4.1 on 2022-09-12 01:55

import django.core.validators
from django.db import migrations, models
import powersystem_tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('powersystem_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=powersystem_tools.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cdf'])]),
        ),
    ]
